# Generated by Django 4.1.7 on 2023-03-20 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0007_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='project_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи проекта'),
        ),
    ]
